- packages/batman
- packages/bobthefish
- packages/budspencer
- packages/chain
- packages/clearance
- packages/cmorrell
- packages/cyan
- packages/dangerous
- packages/edan
- packages/eden
- packages/es
- packages/fishbone
- packages/krisleech
- packages/lambda
- packages/lolfish
- packages/mokou
- packages/nelsonjchen
- packages/red-snapper
- packages/scorphish
- packages/shellder
- packages/simple-ass-prompt
- packages/sushi
- packages/tomita
- packages/vi-mode
* Add some missing theme descriptions (pulled from GitHub)
* Fix typo in vi-mode package file.
> Moar package descriptions

- packages/tweetjay
I would like to share my theme for oh-my-fish with others :)
> Add tweetjay theme for oh-my-fish

- packages/doughsay
I made a simple theme with some nice features: https://github.com/doughsay/omf-theme-doughsay
Would love to have it included!
Thanks! :)
> Add doughsay theme

- packages/colorman
Hey everybody,
first time committing. I hope this is right. The "plugin" is incredibly simple but I thought it'd be nice to have as an easy to install plugin (oh-my-zsh has one).
Please let me know if anything needs to be changed. Cheers :)
> Adding colorman plugin

- packages/wacom-screen
My first humble plugin :) Feel free to tell me If I did something wrong.
https://github.com/TeddyDD/plugin-wacom-screen
> add wacom-screen plugin

- packages/lucky
Opens ELinks with the link of your Google lucky keyword
> Add lucky: Google I'm feeling lucky in your shell

- packages/envious
Added a new package to manage shell environment variables, https://github.com/iamruinous/plugin-envious.
> add github.com/iamruinous/plugin-envious

- packages/fishbone
This PR only updates the maintainer of the [Fishbone theme](https://github.com/oh-my-fish/theme-fishbone)
> Add maintainer of Fishbone theme

- packages/pygmalion
It's my theme from my `zsh` days, I'm moving to a new computer and want to easily reinstall it 😄
> added the pygmalion theme

- packages/home-binpath
- packages/yarn-binpath
Add two plugins, home-binpath and yarn-binpath.
home-binpath will add $HOME/.bin to your path
yarn-binpath will add the result of `yarn global bin` to your path
> add yarn-binpath and home-binpath

- packages/emacs
See https://github.com/oh-my-fish/oh-my-fish/issues/561
> Update emacs package to more recent upstream source

- packages/one
I've seriously updated my theme since last year, and I changed my GitHub name, so I feel like I needed to update this
> "One" theme v2

- packages/bookmark_dir
- packages/package_list
- packages/publish
Good night gals and gents,
I'm looking forward to contribute to other fish users this script of mine. It's called _bookmark_dir_, it bookmarks folders for easy access and path retrieval. Simple as that. Also, this is my first time contributing to omf, so, I'm open for any criticism deemed necessary.
Cheers,
> Initial commit, added plugin description

- packages/neolambda
The prior description was a little wack 🙄
> update description for neolambda theme

- packages/lavender
`Lavender` is a new theme, that simple and elegant.
> A new theme for Oh My Fish

- packages/xcode
This is an in-progress port of the Xcode plugin from Oh My Zsh, intended to eventually include some of my own helper functions from my day-to-day. I wanted to kick things off here with the function I find myself using most often, so hopefully that's sufficient for contribution to the plugin library. 
Please let me know if anything more is required.
> Xcode plugin – utilities for working with Xcode

- packages/bookmark_dir
- packages/package_list
- packages/publish
- packages/words
Modified the packages description accordingly.
> Moved my repos to gitlab

- packages/spacefish
Whoops! Looks like I dropped a couple letters when writing the description last time. 😅
> Fix typo in spacefish description

- packages/random
see https://github.com/oh-my-fish/oh-my-fish/issues/622
> add random theme

- packages/fishingz
I made a fish shell plugin for fast access to all file systems : https://github.com/nekochango/fishingz
I would like to add it to the public repository of oh-my-fish.
> Added fishingz plugin.

- packages/back
- packages/bookmark_dir
- packages/nav
Morning.
I've created a new plugin that combines the functions  of my two previous plugins `bookmark_dir` and `back`. And also something similar to `z`, though that plugin is not mine. As such, I'm requesting to add my latest plugin while removing the two previous ones, as they shall not be maintained.
Thanks.
> Added nav, removed bookmark_dir and back

- packages/flash
- packages/hulk
They didn't make it to Fisher v3, and the repos are nowhere to be found ¯\\\_(ツ)\_/¯ 
Fixes https://github.com/oh-my-fish/oh-my-fish/issues/645
> Remove flash and hulk themes

- packages/sashimi
up to date PR
hi, I made a custom prompt and it may be distributed with omf framewrok.
> add sashimi theme

- packages/insist
- packages/nav
- packages/package_list
- packages/peco_utils
- packages/publish
- packages/words
Hello, I moved my fish scripts to a repository dedicated for that. I might make use of the omf option to add repositories in the future. Added some new scripts as well.
> Moved my fish script to its own repository

- packages/plug
This enables fish shell interactions with vim-plug.
> Adds vim-plug wrapper plugin

- packages/redfish
I've created my theme for `omf` and would like to have it added to the repos. If there's anything else I need to do to fix this I would be happy to incorporate changes .
> add redfish theme to packages

- packages/yadd
I thought that this might be a useful plugin to add. Let me know if it needs any changes or anything.
> add yadd plugin to packages

- packages/homestead
Add config file to add my Laravel Homestead plugin.
> Create homestead plugin

- packages/autovenv
Added my autovenv package to the list. It automatically activates/deactivates Python venvs when entering/leaving a directory, similar to pyenv.
> Added autovenv

- packages/vish
This is a plugin I wrote for personal use a while back - it adds a bunch of vim-like shortcuts, including saving things to "registers" and reusing them. It could use some more work but already has some documentation, so I'm sure it'll be useful to someone besides me :)
> Add vish plugin

- packages/open_github
update description for open_github after extending its functionality to be able to open PRs directly from the command line
> update description for open_github

- packages/boxfish
This is a theme that I think could improve omf's selection of themes due to its simplicity and compact vi mode indicator.
> Add boxfish theme

- packages/platformio
I've made this plugin to get some autocomplete using Platformio's command line interface, it might be useful to other people.
> Add Platformio plugin

- packages/flash
Brings back the Flash theme as per https://github.com/oh-my-fish/oh-my-fish/issues/637
> Bring back Flash theme

- packages/git-refresh
> Switch git-refresh to =

- packages/slacker
A minimalist theme based on theme Clearance & Nelsonjchan!
> theme slacker package added

- .gitattributes
See [this issue](https://github.com/oh-my-fish/packages-main/issues/95).
> Added hints so GitHub properly classifies the code

- packages/solarfish
https://github.com/MrSiliconGuy/theme-solarfish
> Add solarfish theme

- packages/doch
A SFW alternative to the existing [f**k](/oh-my-fish/packages-main/tree/master/packages/fuck) command.
> Add doch plugin

- packages/colored-man-pages
fix a package after the maitiner changed their username
> fix a package after the maitiner changed their username

- packages/colored-man-pages
Checked, fixes update on channel dev, No effect on channel stable.
oh-my-fish/oh-my-fish#872
> Set colored-man-pages branch to main

- packages/litesic
a bash-like classic theme in the sense of the format [<PATH>], and WITHOUT the username, which the user probably knows so its useless.
> New theme "litesic" (lite classic)

- packages/anchor
Hi!
I would like to add a new theme to the package registry called `anchor`.
> Add "anchor" theme

- packages/simple
Hi, I would like to add my `simple` theme to the omf package registry. Please let me know if any changes are needed. Thanks !
> Add simple theme

- packages/neel
Hello, I wanted to add a new theme neel to oh-my-fish.
> added neel theme

- packages/kovial
Kovial is a simple, clean theme.
Signed-off-by: krypticallusion <krypticallusion@gmail.com>
> Add kovial theme

- packages/mint
Hi, I wrote a theme, mint, a fish prompt theme with Linux Mint default bash $PS1.
Thank you for reviewing my codes.
> Add mint theme

- packages/simple
Reverts oh-my-fish/packages-main#149
> Revert "Add simple theme"

- packages/litesic
Reverts oh-my-fish/packages-main#132
> Revert "New theme "litesic" (lite classic)"

- packages/base16
Reverts oh-my-fish/packages-main#171
> Revert "add a theme: base16"

- packages/kovial
> packages/kovial: Update repository URI

- packages/simple
This should fix the issues with Repo URL trailing space. Also enabled Issues with my simple repo.
Thanks!
> Fix for issues reported with Simple theme in #149

- packages/error
This is my first time contributing to OMF, so I apologize in case I did something wrong.
I would appreciate it very much if this got added to the official repo! It's nothing big but I think it can be quite useful sometimes.
Thank you for your time!
> Add error – A simple, light-weight, user-friendly error message handler/printer.

- packages/zoxide
[zoxide](https://github.com/ajeetdsouza/zoxide) is a fast, configurable autojumper written in Rust.
> Add zoxide plugin

- packages/trish
This is an attempt at implementing the FreeDesktop.org Trash spec as a fish plugin, so that one can manage the Trash folder from the command line. 
It's my first serious 'coding' project and my first time doing a pull request, so I hope I did everything alright here =)
Tnx!
> Add trish plugin

- packages/async-prompt
- packages/puffer-fish
Adds those 2 plugins to the repository.
async-prompt: https://github.com/acomagu/fish-async-prompt
puffer-fish: https://github.com/nickeb96/puffer-fish
> adds async-prompt and puffer-fish

- packages/easy-eel
🌊 **Easy Eel theme for Oh My Fish**
**Unveiling** [_Easy Eel_](https://github.com/pgolebiowski/theme-easy-eel), a minimalistic theme for the Fish shell with flexible customization options. Dive into an inviting command line experience, designed for ocean enthusiasts and customization lovers alike.
🌟 **Customization Features**
1. **Environment Variables.** Refine aesthetics with a myriad of variables.
2. **Override Functions.** Modify behavior or replace entire prompt sections as you see fit.
🌅 **Also Featuring**
- 🐠 **Clean Interface.** Sleek and distraction-free.
- 🌊 **Oceanic Greetings.** Get inspired with sea-themed messages every time you open a new terminal session.
I'm excited for the OMF community to experience the depth of customization _Easy Eel_ offers. I truly believe this …
> Add Easy Eel theme to OMF packages

- packages/ai
Adds the magical `ai` plugin to figure out unknown shell commands.
> Add AI plugin
