oh-my-fish/packages-main

packages/asdf

Simple plugin to access asdf without manually messing with config.fish and copying completions file.  See [README](https://github.com/doughsay/omf-asdf) for some more details.

Add asdf plugin.

---

packages/graystatus

I made a modest prompt theme for fish shell : https://github.com/usami-k/graystatus
I would like to add it to the public repository of oh-my-fish.

Add graystatus theme

---

packages/gls

I made a fish shell plugin for GNU ls support on macOS : https://github.com/usami-k/gls
I would like to add it to the public repository of oh-my-fish.

Add gls plugin

---

packages/pisces

From the readme:
> _pisces_ is a plugin for fish that helps you to work with paired symbols like () and '' in the command line. Just as in your favorite text editor!
I [just made](https://github.com/laughedelic/pisces/releases/tag/v0.5.0) it compatible with oh-my-fish and tested that it works using the ohmyfish/ohmyfish docker image.

Add pisces plugin

---

packages/fish_logo

Previously mentioned [HenrikWL/plugin-fish_logo](https://github.com/HenrikWL/plugin-fish_logo) repo was a "port" of my plugin for omf. Since the original plugin is compatible with omf, I'm replacing the clone plugin with the original one.

Fixed fish_logo plugin reference to the original repo

---

packages/separation

Adds a theme which displays a horizontal bar across the terminal for each prompt, visually separating the output of each command. Displays return status (if not 0), username, hostname, and the working directory on the second line. If this string is longer than two fifths of the screen, the prompt is split into a third line, ensuring plenty of space to type commands.

Add theme "separation"

---

packages/enlarge_your_git_alias

This plugin copies each [`git-alias`](https://git-scm.com/book/tr/v2/Git-Basics-Git-Aliases) as abbreviations in [Fish Shell](https://fishshell.com)
[Git Extras](https://github.com/tj/git-extras/blob/master/Installation.md) must be installed

Add: enlarge_your_git_alias plugin

---

packages/bongnoster
packages/last-working-dir

bongnoster is my variety of agnoster that looks more slender imho.
last-working-dir is inspired by the zsh-plugin with the same name. The implementation however uses the --on-variable hook and a universal variable instead of an explicit cache file.

Add bongnoster theme and last-working-dir package

---

packages/neolambda

Add theme **neolambda** based on the lambda theme.  This theme provides an updated fork of the lambda theme.

add neolambda theme to oh-my-fish packages repo

---

packages/keychain

- improves compatibility with OMF
- optimises loading
- allows customising options
- fixes case where SHELL var is not set
Compared to the original keychain package this one uses different default options - just `--quiet`.  All the other options used by the plugin before are in fact a matter of preference and IMHO shouldn't be default, e.g. `--confhost` which reads SSH config to get a list of used keys, but produces a warning if SSH config file isn't found, `--timeout` which clears keys from agent after specified time, can be a bit annoying, and GPG isn't used on every system.
Given that customising options is now as easy as `set -U keychain_init_args --quiet --confhost` and that keychain's options really depend on use-case, I think it makes sense to be less opinionated.

Update keychain package

---

packages/extract

The original package upstream has not been updated in a long time and no longer works.

Change extract package to OMF version

---

packages/fzf

Differences between old and new plugins:
1. New plugin provides shortcuts.
2. New plugin provides commands for opening file/dir using default editor and `xdg-open` or `open` command.
3. New plugin has better documentation.
4. New plugin is updated frequently.

Update fzf plugin

---

packages/feedback

A plugin for formatting feedback messages. Usually in the context of a fish plugin. As such, It's a dependency for most of my plugins, including `nav`, `publish` and `peco_utils`

Add feedback

---

packages/zlua

Features of [z.lua](https://github.com/skywind3000/z.lua):
- **10x** times faster than **fasd** and **autojump**, **3x** times faster than **z.sh**.
- Available for **posix shells**: bash, zsh, dash, sh, ash, busybox and etc.
- Available for Fish Shell, Power Shell and Windows cmd.
- Enhanced matching mode takes you to where ever you want precisely.
- Allow updating database only if `$PWD` changed with "$_ZL_ADD_ONCE" set to 1.
- Interactive selection enables you to choose where to go before cd.
- Interactive selection with FZF (optional).
- Quickly go back to a parent directory instead of typing "cd ../../..".
People using [z.lua](https://github.com/skywind3000/z.lua) said:
- "I like this in principal. I’m pretty damn predictable at the command line and far too lazy to make shortcuts"
- …

add: z.lua - A new cd command that helps you navigate faster by learning your habits

---

packages/git-refresh

**git-refresh** automates the workflow of updating git repositories as soon
as we cd to them.
Hail Automation! :) Hope it saves you some time and hopefully some frustration.
Project aim is that you never see the following nasty git error warning ever again.
The project aim is that you never see the following git error warning 
```
To https://github.com/USERNAME/REPOSITORY.git
! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/USERNAME/REPOSITORY.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
```

Add git-refresh plugin

---

packages/remove_host

The PR adds a plugin that adds a `remove_host` function, convenient for removing host keys from specific lines numbers in `~/.ssh/known_hosts`.

Add remove_host plugin

---

packages/uid-gid

This is a simple plugin to expose the classic bash variables `$UID` and `$GID` as global env vars.
It is sometimes useful with some tools (i.e. Docker).

Add uid-gid plugin

---

packages/makeme

Added MakeMe / MakeMeFish.
MakeMeFish is a plugin that allows you to easily navigate and preview make targets, using fzf.
The features of MakeMeFish is carefully thought out to do what the user expects it to, regardless of if there is 5, 10 or 100 targets. MakeMeFish lists targets in an expected order where true phony targets get listed first, while file targets and generated targets get listed below. 
The preview allows you to see what the target will actually execute. Interactive mode allows you to run the same target or adjacent targets without leaving MakeMeFish.
Run MakeMeFish with the command `mm` and print the options by running `mm -h` or `mm --help`

Added MakeMeFish

---

packages/enhancd

> The new cd command called "enhancd" enhanced the flexibility and usability for a user. enhancd will memorize all directories visited by a user and use it for the pathname resolution. If the log of enhancd have more than one directory path with the same name, enhancd will pass the candidate directories list to the filter within the ENHANCD_FILTER environment variable in order to narrow it down to one directory
I'm not the author of this plugin (it's @b4b4r07), i just ported it to fish :heart: :fish:

Add enhancd plugin

---

packages/ghcup

Introduces an [ghcup](https://www.haskell.org/ghcup/) (a Haskell toolchain manager) integration plugin.

Add ghcup plugin

---

packages/ansible
packages/artisan
packages/ays
packages/barracuda
packages/bongnoster
packages/homestead
packages/keychain
packages/mish
packages/node
packages/open_github
packages/pastfish
packages/pcd
packages/pure
packages/random
packages/redfish
packages/shellder
packages/solarfish
packages/spacefish
packages/termux
packages/uid-gid
packages/yadd
packages/zeit

This:
- Removes archived packages because they are likely to be out of date, broken, of no interest to anyone
- Removes packages without an issue tracker, because they leave users no way to report bugs (except for oh-my-fish packages, because they can report to oh-my-fish itself)
- Updates the URLs on moved packages
Only for packages on github because I wrote a small script that crawls the API.
Obsoletes #150,

Clean up packages

---

packages/solarfish

Updated version of #150
Thanks to #151, the repo link for solarfish is correct. However, the maintainer and email are still out-of-date.
This PR correctly follows the `maintainer = YOUR-NAME <YOUR-EMAIL>` format as specified in README.md

Update solarfish maintainer

---

packages/fonts

An additional type = plugin had split a string onto multiple lines.

Fix broken configuration

---

packages/fish-top

This new plugin adds the ability to list top used commands for Fish Shell.

Add new plugin fish-top
